### ISSUE TITLE
Error while running tutorial 10

### ISSUE THREAD

**Issue by wangg12** [jcteng/opengl-tutorial#1]
@jcteng Do you have any idea what the problem is?
```
Traceback (most recent call last):
  File "tu_10_normal_mapping.py", line 258, in <module>
    textureName=["resources/tu10/diffuse.DDS", "resources/tu10/normal.bmp", "resources/tu10/specular.DDS"]))
  File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/meshViewer.py", line 19, in add_mesh
    self.meshes.append(meshWithRender.makeContext())
  File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/meshViewer.py", line 79, in makeContext
    self.loadTexture()
  File "tu_10_normal_mapping.py", line 168, in loadTexture
    DiffuseTexture = textureLoader(self.textureName[0])
  File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/textureLoader.py", line 94, in __init__
    self.loadDDS(fname)
  File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/textureLoader.py", line 61, in loadDDS
    ddsbuffer[offset:offset + size])
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6338)
  File "wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call (src/wrapper.c:2984)
  File "wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2536)
  File "wrapper.pyx", line 66, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2463)
  File "/data/wanggu/anaconda3/envs/py27/lib/python2.7/site-packages/OpenGL/GL/images.py", line 500, in __call__
    return arrays.ArrayType.arrayByteCount( arg )
AttributeError: ("'module' object has no attribute 'ArrayType'", 6, <OpenGL.platform.baseplatform.glCompressedTexImage2D object at 0x7f4a5e83b8c0>)
```

**Comment by penincillin** [comment]
@wangg12  
I encountered the same problem. Have you resolved it ?
Thanks !

**Comment by lion117** [comment]
> @jcteng Do you have any idea what the problem is?
> 
> ```
> Traceback (most recent call last):
>   File "tu_10_normal_mapping.py", line 258, in <module>
>     textureName=["resources/tu10/diffuse.DDS", "resources/tu10/normal.bmp", "resources/tu10/specular.DDS"]))
>   File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/meshViewer.py", line 19, in add_mesh
>     self.meshes.append(meshWithRender.makeContext())
>   File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/meshViewer.py", line 79, in makeContext
>     self.loadTexture()
>   File "tu_10_normal_mapping.py", line 168, in loadTexture
>     DiffuseTexture = textureLoader(self.textureName[0])
>   File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/textureLoader.py", line 94, in __init__
>     self.loadDDS(fname)
>   File "/data/wanggu/PoseEst/python-opengl-tutorial/utils/textureLoader.py", line 61, in loadDDS
>     ddsbuffer[offset:offset + size])
>   File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
>   File "wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6338)
>   File "wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call (src/wrapper.c:2984)
>   File "wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2536)
>   File "wrapper.pyx", line 66, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2463)
>   File "/data/wanggu/anaconda3/envs/py27/lib/python2.7/site-packages/OpenGL/GL/images.py", line 500, in __call__
>     return arrays.ArrayType.arrayByteCount( arg )
> AttributeError: ("'module' object has no attribute 'ArrayType'", 6, <OpenGL.platform.baseplatform.glCompressedTexImage2D object at 0x7f4a5e83b8c0>)
> ```

hi, I had problem with the demo 5 . those demos only 1 and 2 could run . 
>  I use py37 , and intel i-4950 without indepent graphiccard . use intel integrated graphic card . 
the error is 
```
Traceback (most recent call last):
  File "src\wrapper.pyx", line 66, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "D:\Anaconda3\lib\site-packages\OpenGL\GL\images.py", line 499, in __call__
    return arraydatatype.ArrayDatatype.arrayByteCount(arg)
  File "src\arraydatatype.pyx", line 257, in OpenGL_accelerate.arraydatatype.ArrayDatatype.arrayByteCount
AttributeError: ("'NumberHandler' object has no attribute 'arrayByteCount'", 6, <OpenGL.platform.baseplatform.glCompressedTexImage2D object at 0x000000000BD590D8>)
```

#### How did you solve this problem?

**Comment by jcteng** [comment]
this demo only works on python27x ,do not use python3x
